### ISSUE TITLE
Question: iOS version release

### ISSUE THREAD

**Issue by JaWeilBaum** [kreativzirkel/coronika#4]

**Comment by JayBrown** [comment]
Apple tends to prohibit health & WuFlu apps, unless they come from registered/trusted health authorities or providers. They blocked even simple COVID-19 info apps that were just GUI frontends for public APIs with official health data. Maybe that's what's happening here? If so, it would be nice to have an ipa for download, so we can at least sideload the app.

**Comment by leonhillebrandt** [comment]
@JaWeilBaum It is exactly like @JayBrown said. The iOS version of our app was ready months ago together with the first release for Android. But we are trying find a way to get into the Apple App Store.

**Comment by lhillebrandt** [comment]
@JaWeilBaum It is exactly like @JayBrown said. The iOS version of our app was ready months ago together with the first release for Android. But we are trying find a way to get into the Apple App Store.

**Comment by lhillebrandt** [comment]
@JayBrown Here you go:
[coronika.ipa.zip](https://github.com/kreativzirkel/coronika/files/5428601/coronika.ipa.zip)

**Comment by lhillebrandt** [comment]
@JaWeilBaum @JayBrown 
Finally the app is available in the Apple App Store: [https://apps.apple.com/de/app/coronika/id1538427759](https://apps.apple.com/de/app/coronika/id1538427759)
