### ISSUE TITLE
Make picking the time of a location easier

### ISSUE THREAD

**Issue by oerms** [kreativzirkel/coronika#6]
With the last update (v2.0.0.) you changed the time picker from the clock-like input to a roller-like (I don't know how those are called...).

This is way more inconvenient than the clock input. Please bring it back. It was much faster.

I can only speak for myself, but it makes entering my locations no fun at all anymore and I will likely stop doing it...

Thanks for you consideration.

**Comment by josephbadow** [comment]
+1

I agree, I just came here to request the old time picker as well.

**Comment by lhillebrandt** [comment]
@oerms @josephbadow The latest update (v2.0.3) brings back the old time picker.

**Comment by josephbadow** [comment]
Thank you @lhillebrandt, that was quick. By the way I also appreciate that the phone number is no longer a  required field for a contact.

**Comment by lhillebrandt** [comment]
@josephbadow This is also part of the latest update.

**Comment by oerms** [comment]
<3
